name: Snyk Ruby
on: 
  workflow_dispatch:
    inputs:
      purpose:
        description: 'Purpose'     
        required: true
        default: 'test'
  pull_request: {}
  push: {}
  schedule:
  - cron: '0 0 * * 0'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
# This manipulates what threshold to report on
# See here for more information: https://github.com/snyk/actions/tree/master/ruby
#        with:
#          args: --severity-threshold=high
